import { createId, parseId, type OpaqueId } from "../../../domain/src/index.js";

export type SecretProvider = "aws" | "azure" | "gcp" | "local" | "vault";
export interface SecretReference { readonly createdAt: string; readonly deletedAt: string | null; readonly id: OpaqueId<"secret_reference">; readonly lastUsedAt: string | null; readonly locatorHash: string; readonly name: string; readonly organizationId: OpaqueId<"organization">; readonly provider: SecretProvider; readonly providerVersion: string | null; readonly rotatedAt: string | null; readonly targetId: OpaqueId<"target">; }
export interface SecretRepository { insert(reference: SecretReference): Promise<void>; get(organizationId: OpaqueId<"organization">, id: OpaqueId<"secret_reference">): Promise<SecretReference | undefined>; update(reference: SecretReference): Promise<void>; list(organizationId: OpaqueId<"organization">, targetId: OpaqueId<"target">): Promise<readonly SecretReference[]>; }
export interface SecretAudit { record(input: { readonly action: string; readonly organizationId: string; readonly targetId: string; readonly targetType: string }): Promise<void>; }

export class SecretReferenceService {
  private readonly audit: SecretAudit | undefined; private readonly clock: () => Date; private readonly repository: SecretRepository;
  constructor(options: { readonly audit?: SecretAudit; readonly clock?: () => Date; readonly repository: SecretRepository }) { this.audit = options.audit; this.clock = options.clock ?? (() => new Date()); this.repository = options.repository; }
  async create(input: { readonly organizationId: string; readonly targetId: string; readonly name: string; readonly provider: SecretProvider; readonly locatorHash: string; readonly providerVersion?: string }): Promise<SecretReference> {
    if (!/^[a-z][a-z0-9_-]{2,63}$/u.test(input.name)) throw new Error("Invalid secret reference name.");
    if (!/^[0-9a-f]{64}$/u.test(input.locatorHash)) throw new Error("Locator hash must be SHA-256.");
    const organizationId = parseId("organization", input.organizationId); const targetId = parseId("target", input.targetId); const now = this.clock().toISOString();
    const reference: SecretReference = Object.freeze({ createdAt: now, deletedAt: null, id: createId("secret_reference"), lastUsedAt: null, locatorHash: input.locatorHash, name: input.name, organizationId, provider: input.provider, providerVersion: input.providerVersion ?? null, rotatedAt: null, targetId });
    await this.repository.insert(reference); await this.audit?.record({ action: "secret_reference.created", organizationId, targetId: reference.id, targetType: "secret_reference" }); return reference;
  }
  list(organizationId: string, targetId: string) { return this.repository.list(parseId("organization", organizationId), parseId("target", targetId)); }
  async markUsed(organizationId: string, id: string): Promise<SecretReference> { const reference = await this.get(organizationId, id); if (reference.deletedAt) throw new Error("Secret reference is deleted."); const updated = Object.freeze({ ...reference, lastUsedAt: this.clock().toISOString() }); await this.repository.update(updated); return updated; }
  async rotate(organizationId: string, id: string, locatorHash: string, providerVersion?: string): Promise<SecretReference> { if (!/^[0-9a-f]{64}$/u.test(locatorHash)) throw new Error("Locator hash must be SHA-256."); const reference = await this.get(organizationId, id); if (reference.deletedAt) throw new Error("Secret reference is deleted."); const updated = Object.freeze({ ...reference, locatorHash, providerVersion: providerVersion ?? reference.providerVersion, rotatedAt: this.clock().toISOString() }); await this.repository.update(updated); await this.audit?.record({ action: "secret_reference.rotated", organizationId: reference.organizationId, targetId: reference.id, targetType: "secret_reference" }); return updated; }
  async remove(organizationId: string, id: string): Promise<void> { const reference = await this.get(organizationId, id); if (reference.deletedAt) return; await this.repository.update(Object.freeze({ ...reference, deletedAt: this.clock().toISOString() })); await this.audit?.record({ action: "secret_reference.deleted", organizationId: reference.organizationId, targetId: reference.id, targetType: "secret_reference" }); }
  private async get(organizationId: string, id: string): Promise<SecretReference> { const reference = await this.repository.get(parseId("organization", organizationId), parseId("secret_reference", id)); if (!reference) throw new Error("Secret reference not found."); return reference; }
}

export class InMemorySecretRepository implements SecretRepository { private readonly references = new Map<string, SecretReference>(); insert(reference: SecretReference): Promise<void> { if ([...this.references.values()].some((candidate) => candidate.organizationId === reference.organizationId && candidate.targetId === reference.targetId && candidate.name === reference.name && !candidate.deletedAt)) return Promise.reject(new Error("Secret reference already exists.")); this.references.set(reference.id, reference); return Promise.resolve(); } get(organizationId: OpaqueId<"organization">, id: OpaqueId<"secret_reference">) { const reference = this.references.get(id); return Promise.resolve(reference?.organizationId === organizationId ? reference : undefined); } update(reference: SecretReference): Promise<void> { this.references.set(reference.id, reference); return Promise.resolve(); } list(organizationId: OpaqueId<"organization">, targetId: OpaqueId<"target">) { return Promise.resolve([...this.references.values()].filter((reference) => reference.organizationId === organizationId && reference.targetId === targetId && !reference.deletedAt)); } }
