function literal(value) {
  return JSON.stringify(value);
}

function propertyType(schema) {
  if ("const" in schema) return literal(schema.const);
  if (Array.isArray(schema.enum)) return schema.enum.map(literal).join(" | ");
  if (Array.isArray(schema.oneOf))
    return schema.oneOf.map(propertyType).join(" | ");
  if (schema.type === "string") return "string";
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "null") return "null";
  if (schema.type === "array")
    return `readonly ${propertyType(schema.items)}[]`;
  if (schema.type === "object" && schema.properties) return objectType(schema);
  if (
    schema.type === "object" &&
    typeof schema.additionalProperties === "object"
  ) {
    return `Readonly<Record<string, ${propertyType(schema.additionalProperties)}>>`;
  }
  if (schema.type === "object") return "Readonly<Record<string, unknown>>";
  return "unknown";
}

function objectType(schema) {
  const required = new Set(schema.required ?? []);
  const lines = Object.entries(schema.properties ?? {}).map(
    ([name, value]) =>
      `  readonly ${JSON.stringify(name)}${required.has(name) ? "" : "?"}: ${propertyType(value)};`,
  );
  return `{\n${lines.join("\n")}\n}`;
}

export function generateSchemaTypes(registry) {
  const declarations = registry.map(
    ({ schema, typeName }) =>
      `export interface ${typeName} ${objectType(schema)}`,
  );
  return `// Generated by scripts/generate.mjs. Do not edit.\n\n${declarations.join("\n\n")}\n`;
}
